### ISSUE TITLE
[FTBS] adplug package configuration name incorrectly specified in adplug project file

### ISSUE THREAD

**Issue by Corin-EU** [TTK-qmmp/qmmp-adplug#1]
On line 20 of the /adplug project file ädplug.pro it states

                   PKGCONFIG += libadplug

this causes qmake to invoke pkg-config to look for the file libadplug.pc which does not exist and so qmake exits with the error

                  Project ERROR: libadplug development package not found

The source code of the latest version of  AdPlug  v2.3.3 and the latest Github master at

                <https://github.COM/adplug/adplug>

have the name of the package configuration file as "adplug.pc" not "libadplug.pc"

Searching on the Debian package website for adplug reveals "pkgconfig/adplug.pc", so Debian have not rename the file in their development packages.

Changing line 20 of adplug.pro to

                PKGCONFIG += adplug

resolves this issue.

**Comment by Greedysky** [comment]
Fixed, Thank you.
