### ISSUE TITLE
[FTBS] qmmp-adplug latest r.c1aed04 with qmmp latest v2.1.9 and Qt6 (v6.6.3) -- qmmp::configFile() exists no more

### ISSUE THREAD

**Issue by Corin-EU** [TTK-qmmp/qmmp-adplug#2]
I have upgraded my QMMP installation to the latest version v2.1.9 and built with Qt6 (v6.6.3) so I am now trying to build the optional extra plugins.

Building fails on compiling addhelper.cpp

` 
g++-13 -c -pipe -O2 -std=gnu++1z -D_REENTRANT -w -fPIC -DQT_NO_DEBUG -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I/usr/local/include -I/usr/local/include/libbinio -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I. -I. -I/usr/include/qt6/QtWidgets -I/usr/local/include/libbinio -I/usr/local/include/qmmp -I/usr/include -I/usr/lib64/qt6/mkspecs/linux-g++ -o adplughelper.o adplughelper.cpp

adplughelper.cpp: In constructor ‘AdPlugHelper::AdPlugHelper(const QString&)’:

adplughelper.cpp:15:30: error: ‘configFile’ is not a member of ‘Qmmp’
   15 |     QSettings settings(Qmmp::configFile(), QSettings::IniFormat);
 ......|.................................................^~~~~~~~~~

make: *** [Makefile:486: adplughelper.o] Error 1
`

In going from QMMP version 1 (Qt5) to QMMP version 2 (Qt6), the function static QString configFile() is no longer present in the include file qmmp.h

Would you consider upgrading qmmp-adplugin to also allow compilation with QMMP version 2 as Qt6 (first released back in December 2020)  is now becoming the more predominant version?

**Comment by Greedysky** [comment]
Fixed @Corin-EU
